# ipssh configuration
#
# This file is installed to:
# %APPDATA%\ipssh\config.toml

paste_hotkey = "ctrl+v"
remote_dir = "~/Pictures/paste-ssh"
image_format = "png"
non_image_paste = "text"
template = "{remote_path}"

[upload]
filename_pattern = "{timestamp}-{random}.{ext}"
